2.2创建数组

In [447]:
import numpy as np

In [448]:
# 一维数组
arr1d = np.array([1, 2, 3])
arr1d

array([1, 2, 3])

In [449]:
# 二维数组
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [450]:
# 三维数组
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [451]:
# 全为0的数组
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [452]:
# 全为1的数组
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [453]:
# 创建数组，只分配内存空间，填充元素随机
np.empty((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [454]:
# 创建等差数组，结果是一维数组而非列表,左闭右开（start, end, step）
np.arange(1, 20, 5)

array([ 1,  6, 11, 16])

In [455]:
# 创建等差数组，左闭右闭（start, end, size)
e = np.linspace(1, 20, 5)
e
len(e)

5

In [456]:
# dtype参数显式指明元素的类型
np.array([1, 2, 3], dtype = np.float32)

array([1., 2., 3.], dtype=float32)

In [457]:
np.ones((3, 3), dtype = 'int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

2.3 数组的数据类型

In [458]:
# 查看数据类型
data = np.array([[1, 2, 3], [4, 5, 6]])
data.dtype.name

'int32'

In [459]:
# 转换数据类型
# 将数据类型int32转换为float32
float_data = data.astype(np.float32)
float_data.dtype.name

'float32'

In [460]:
float_data = np.array([1.2, 2.9, 3.5])
float_data

array([1.2, 2.9, 3.5])

In [461]:
# float32转换为int32会丢失精度（只取整数部分，小数部分舍去）
int_data = float_data.astype(np.int32)
int_data

array([1, 2, 3])

In [462]:
# astype将字符串类型转换为整数类型
str_data = np.array(['1', '2', '3'])
int_data = str_data.astype(np.int64)
int_data

array([1, 2, 3], dtype=int64)

2.4 数组的索引和切片

In [463]:
# 整数索引和切片
arr2d = np.array([[1, 6, 11, 16, 21], [2, 7, 12, 17, 22], [3, 8, 13, 18, 23], [4, 9, 14, 19, 24], [5, 10, 15, 20, 25]])
arr2d

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [464]:
arr2d[2]

array([ 3,  8, 13, 18, 23])

In [465]:
arr2d[2, 1]

8

In [466]:
# 右开
arr2d[:2]

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22]])

In [467]:
arr2d[:2, :2]

array([[1, 6],
       [2, 7]])

In [468]:
arr2d[:, 2]# 列索引为2的整列元素

array([11, 12, 13, 14, 15])

In [469]:
# 花式索引
arr = np.array([10, 6, 5, 11, 18, 16, 9, 0, 3, 20])
arr[[0, 1, 5]]

array([10,  6, 16])

In [470]:
arr2d
arr2d[[1, 4]] # 行索引为1、4的元素

array([[ 2,  7, 12, 17, 22],
       [ 5, 10, 15, 20, 25]])

In [471]:
arr2d[[1, 4], [2, 3]] # 选取第2行第3列，第5行第4列的元素

array([12, 20])

In [472]:
# 布尔索引
student_score = np.array([[79, 88, 80], [89, 90, 92], [83, 78, 85], [78, 76, 80]])
student_score

array([[79, 88, 80],
       [89, 90, 92],
       [83, 78, 85],
       [78, 76, 80]])

In [473]:
student_score > 80

array([[False,  True, False],
       [ True,  True,  True],
       [ True, False,  True],
       [False, False, False]])

In [474]:
student_score[student_score > 80]

array([88, 89, 90, 92, 83, 85])

In [475]:
# 布尔索引可与切片混合使用
student_score[[True, False, True, False], :2] # 第一、三行，前两列

array([[79, 88],
       [83, 78]])

2.5数组的算数运算

In [476]:
# 形状相同的数组间的算术运算
arr_1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr_2 = np.array([[2, 3, 4, 5], [6, 7, 8, 9], [10, 11, 12, 13]])

In [477]:
arr_1 + arr_2

array([[ 3,  5,  7,  9],
       [11, 13, 15, 17],
       [19, 21, 23, 25]])

In [478]:
arr_1 - arr_2

array([[-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

In [479]:
arr_1 * arr_2

array([[  2,   6,  12,  20],
       [ 30,  42,  56,  72],
       [ 90, 110, 132, 156]])

In [480]:
arr_1 / arr_2

array([[0.5       , 0.66666667, 0.75      , 0.8       ],
       [0.83333333, 0.85714286, 0.875     , 0.88888889],
       [0.9       , 0.90909091, 0.91666667, 0.92307692]])

In [481]:
# 形状不同的数组间的算数运算
# 形状兼容则触发“广播机制”，对参与运算的数组进行拓展（两者中取最大），使拓展后的数组具有相同的形状，使之可以进行算术运算
# 形状兼容的条件（任意一个即可）：（1）维度相等（2）有一方维度为1
# A:5*4
# B:  4
# A()B:5*4
# C:8*1*6*1
# D:  7*1*5
# C()D:8*7*6*5

In [482]:
arr_1 = np.array([[1], [5], [9]])
arr_1.shape

(3, 1)

In [483]:
arr_1

array([[1],
       [5],
       [9]])

In [484]:
arr_2 = np.array([1, 2, 3, 4])
arr_2.shape

(4,)

In [485]:
arr_2

array([1, 2, 3, 4])

In [486]:
arr_res = arr_1 + arr_2
arr_res.shape

(3, 4)

In [487]:
arr_res

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [488]:
# 数组与标量的算术运算

In [489]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
data = 10

In [490]:
arr_2d + data

array([[11, 12, 13],
       [14, 15, 16]])

In [491]:
arr_2d - data

array([[-9, -8, -7],
       [-6, -5, -4]])

In [492]:
arr_2d * data

array([[10, 20, 30],
       [40, 50, 60]])

In [493]:
arr_2d / data

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

2.6通用函数

一元通用函数

In [494]:
arr_int = np.array([1, -5, 8, -10])
arr_float = np.array([1.3, -5.5, 8.0, -10.7])
arr_bool = np.array([np.NAN, np.NAN, 8.0, -10.7])
np.fabs(arr_int)

array([ 1.,  5.,  8., 10.])

In [495]:
np.square(arr_int) # 计算数组中各元素的平方

array([  1,  25,  64, 100])

In [496]:
np.ceil(arr_float) # 计算数组中各元素的ceilling值

array([  2.,  -5.,   8., -10.])

In [497]:
np.floor(arr_float) # 计算数组中各元素的floor值

array([  1.,  -6.,   8., -11.])

In [498]:
np.rint(arr_float) # 计算数组中各元素四舍五入的值

array([  1.,  -6.,   8., -11.])

In [499]:
np.modf(arr_float) # 计算数组中各元素的小数部分和整数部分

(array([ 0.3, -0.5,  0. , -0.7]), array([  1.,  -5.,   8., -10.]))

In [500]:
np.isnan(arr_bool) # 判断数组中各元素的值是否为NaN

array([ True,  True, False, False])

二元通用函数

In [501]:
arr_one = np.array([1, 5, 10, 4])
arr_two = np.array([6, 2, 8, 9])

In [502]:
np.add(arr_one, arr_two) # 各元素相加

array([ 7,  7, 18, 13])

In [503]:
np.maximum(arr_one, arr_two) # 各元素的最大值

array([ 6,  5, 10,  9])

In [504]:
np.mod(arr_one, arr_two) # 各元素求模

array([1, 1, 2, 4])

In [505]:
np.less_equal(arr_one, arr_two) # 比较数组arr_one是否小于或等于arr_two。arr_one <= arr_two ?

array([ True, False, False,  True])

2.7数组的重塑与转置

数组的重塑

In [506]:
array_1d = np.arange(1, 13)
print('原数组的形状：' + str(array_1d.shape))
print(array_1d)

原数组的形状：(12,)
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [507]:
array_2d = array_1d.reshape((6, 2))
print('新数组的形状：' + str(array_2d.shape))
print(array_2d)

新数组的形状：(6, 2)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [508]:
new_array_2d = array_2d.reshape((3, 4))
print('新数组的形状：' + str(new_array_2d.shape))
print(new_array_2d)

新数组的形状：(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


数组的转置

In [509]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [510]:
arr.shape

(3, 4)

In [511]:
arr.T # 使用T属性对数组进行转置

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [512]:
arr = np.arange(24).reshape((2, 3, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [513]:
# 使用transpose()方法对数组进行转置，并传入轴编号的元组(轴编号中的元素的顺序默认是0、1、2)
arr.transpose((0, 1, 2))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [514]:
new_arr = arr.transpose((1, 0, 2))
new_arr

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [515]:
new_arr.shape

(3, 2, 4)

In [516]:
new_arr = arr.transpose((0, 2, 1))
new_arr

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

In [517]:
new_arr.shape

(2, 4, 3)

2.8数组的其他操作

条件逻辑

In [518]:
arr_x = np.array([1, 5, 7])
arr_y = np.array([2, 6, 8])
arr_con = np.array([True, False, True])

In [519]:
result = np.where(arr_con, arr_x, arr_y) # 以con为标准，使用x的元素，如果为False则用y的元素
result

array([1, 6, 7])

统计运算

In [520]:
arr = np.arange(10)

In [521]:
arr.sum()

45

In [522]:
arr.mean()

4.5

In [523]:
arr.min()

0

In [524]:
arr.max()

9

In [525]:
arr.argmin() # 最小值的索引

0

In [526]:
arr.argmax() # 最大值的索引

9

In [527]:
arr.cumsum() # 计算元素的累加和

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [528]:
arr.cumprod() # 计算元素的累乘积

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

数组元素排序

In [529]:
arr = np.array([[6, 2, 7], [3, 6, 2], [3, 6, 2], [4, 3, 2]])
arr

array([[6, 2, 7],
       [3, 6, 2],
       [3, 6, 2],
       [4, 3, 2]])

In [530]:
arr.sort() # 注意：sort()方法会修改数组本身
arr

array([[2, 6, 7],
       [2, 3, 6],
       [2, 3, 6],
       [2, 3, 4]])

In [531]:
arr = np.array([[6, 2, 7], [3, 6, 2], [3, 6, 2], [4, 3, 2]])
arr.sort(0) # 沿着编号为0的轴对元素排序
arr

array([[3, 2, 2],
       [3, 3, 2],
       [4, 6, 2],
       [6, 6, 7]])

检索数组元素是否满足条件

In [532]:
arr = np.array([[1, -2, -7], [-3, 6, 2], [-4, 3, 2]])
arr

array([[ 1, -2, -7],
       [-3,  6,  2],
       [-4,  3,  2]])

In [533]:
# any()函数用于判断整个数组中的元素至少有一个满足条件
np.any(arr > 0)

True

In [534]:
# all()函数用于判断整个数组中的元素的值是否全部满足条件
np.all(arr > 0)

False

查找数组的唯一元素

In [535]:
# unique()函数用于找出数组中的唯一元素，并返回一个升序排列的数组
arr = np.array([12, 11, 34, 23, 12, 8, 11])
np.unique(arr)

array([ 8, 11, 12, 23, 34])

判断元素是否在其他数组中

In [ ]:
# in1d(ar1, ar2, assume_unique = False, invert = False)(1为数字1)
# ar1为待判断的数组，ar2为判断ar1的每个元素所依据的值，assume_unique为是否假设数组ar1的唯一性，默认值为False，invert为是否倒转数组的元素，默认值为False

In [536]:
arr = np.array([12, 11, 34, 23, 12, 8, 11])
arr2 = np.array([11,12])
np.in1d(arr, arr2)

array([ True,  True, False, False,  True, False,  True])

线性代数模块

In [537]:
# dot()方法用于矩阵乘法
arr_x = np.array([[1, 2, 3], [4, 5, 6]])
arr_y = np.array([[1, 2], [3, 4], [5, 6]])
arr_x.dot(arr_y) # 等价于np.dot(arr_x, arr_y)

array([[22, 28],
       [49, 64]])

随机数模块

In [538]:
np.random.rand(3, 3)

array([[0.5058033 , 0.19177702, 0.84531867],
       [0.12036092, 0.54849411, 0.8472009 ],
       [0.90426935, 0.67374857, 0.32727166]])

In [539]:
np.random.rand(2, 3, 3)

array([[[0.19099385, 0.99340694, 0.66119277],
        [0.33209755, 0.70200926, 0.4003347 ],
        [0.46125229, 0.90856532, 0.4710711 ]],

       [[0.28207137, 0.99704661, 0.03036109],
        [0.30756431, 0.80797275, 0.24619539],
        [0.08680568, 0.5157594 , 0.66252576]]])

In [540]:
# seed()作用和rand()相同
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [541]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

2.11案例：计算股票收益率和波动率

In [1]:
from numpy import *
# 准备股票数据
closing_price = [336.1, 339.32, 345.03, 344.32, 343.44, 346.5, 351.88, 355.2, 358.16, 354.54, 356.85, 359.18, 359.9, 363.13, 358.3, 350.56, 338.61, 342.62, 342.88, 348.16, 353.21, 349.31, 352.12, 359.56, 360.00, 355.36, 355.76, 352.47, 346.67, 351.99]
closing_price_arr = array(closing_price)
closing_price_arr

array([336.1 , 339.32, 345.03, 344.32, 343.44, 346.5 , 351.88, 355.2 ,
       358.16, 354.54, 356.85, 359.18, 359.9 , 363.13, 358.3 , 350.56,
       338.61, 342.62, 342.88, 348.16, 353.21, 349.31, 352.12, 359.56,
       360.  , 355.36, 355.76, 352.47, 346.67, 351.99])

In [2]:
# 计算简单收益率
returns = diff(closing_price_arr) / closing_price_arr[:-1]
# 查看正的收益率
returns[where(returns > 0)]

array([0.00958048, 0.01682777, 0.00890985, 0.0155267 , 0.00943503,
       0.00833333, 0.00651548, 0.00652935, 0.00200457, 0.00897472,
       0.01184253, 0.00075886, 0.01539897, 0.01450483, 0.00804443,
       0.02112916, 0.00122372, 0.00112562, 0.01534601])

In [3]:
# 计算对数收益率
log_returns = diff(log(closing_price_arr))
# 查看正的收益率
log_returns[where(log_returns > 0)]

array([0.00953488, 0.01668775, 0.00887039, 0.01540739, 0.0093908 ,
       0.0082988 , 0.00649435, 0.00650813, 0.00200256, 0.00893468,
       0.01177296, 0.00075857, 0.01528161, 0.01440064, 0.00801225,
       0.02090904, 0.00122297, 0.00112499, 0.01522945])

In [4]:
# 计算年波动率
annual_volatility = std(log_returns / mean(log_returns) / sqrt(1/252))
print('年波动率：',annual_volatility)

年波动率： 129.2747899111513


In [5]:
# 计算月波动率
monthly_volatility = annual_volatility * sqrt(1/12)
print('月波动率：',monthly_volatility)

月波动率： 37.31841737731776
